package com.csgo.Utils.Enums;

public enum EWeaponType
{
	WEAPONTYPE_KNIFE,
	WEAPONTYPE_PISTOL,
	WEAPONTYPE_SUBMACHINEGUN,
	WEAPONTYPE_RIFLE,
	WEAPONTYPE_SHOTGUN,
	WEAPONTYPE_SNIPER,
	WEAPONTYPE_MACHINEGUN,
	WEAPONTYPE_HEAVYPISTOL,
	WEAPONTYPE_AUTONOOB;

    public int value = ordinal();
};
